Application:
    Port: 8080
Authorization:
    Expiration: 3600
    Encoding: Wow, much safe
    AuthorizationHeader: Authorization
    ExcludedPaths:
        - /user/register
        - /user/login
Database:
    Type: sqlite
    Host: file::memory:?cache=shared